
import { NextRequest, NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import { verifyToken } from "@/lib/auth";
import { ApiResponse } from "@/lib/api-response";

export async function POST(req: NextRequest) {
    try {
        await dbConnect();
        const user = await verifyToken(req);
        if (!user) return ApiResponse.unauthorized();

        const { prompt } = await req.json();

        if (!prompt) {
            return ApiResponse.error("Prompt required", null, 400);
        }

        // Mock AI generation
        const responseData = {
            subject: `[AI] ${prompt.slice(0, 30)}...`,
            html: `
        <div style="font-family: sans-serif; padding: 40px; background-color: #f9fafb; border-radius: 12px; border: 1px solid #e5e7eb;">
            <h1 style="color: #111827; font-size: 24px; font-weight: 700; margin-bottom: 16px;">
                Personalized response for: ${prompt}
            </h1>
            <p style="color: #4b5563; font-size: 16px; line-height: 1.5; margin-bottom: 24px;">
                Thank you for your interest. We've used our AI assistant to draft this template based on your request.
            </p>
            <a href="#" style="display: inline-block; background-color: #4f46e5; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600;">
                Get Started Now
            </a>
            <p style="margin-top: 32px; font-size: 12px; color: #9ca3af;">
                Generated by Email Sender AI Assistant
            </p>
        </div>
        `,
            category: "promo"
        };

        // Simulate delay
        await new Promise(r => setTimeout(r, 1200));

        return ApiResponse.success(responseData);

    } catch (error: any) {
        return ApiResponse.error("AI Generation failed", error);
    }
}
