import {
  Body,
  Controller,
  Get,
  Post,
  Patch,
  Param,
} from "@nestjs/common"
import { InjectModel } from "@nestjs/mongoose"
import { Model } from "mongoose"
import { Template, TemplateDocument } from "./template.schema"

@Controller("templates")
export class TemplatesController {
  constructor(
    @InjectModel(Template.name)
    private readonly templateModel: Model<TemplateDocument>
  ) {}

  // ➕ Create Template (EXISTING)
  @Post()
  async create(@Body() body: any) {
    if (!body.name || !body.subject || !body.html) {
      throw new Error("All fields required")
    }

    return this.templateModel.create({
      name: body.name,
      subject: body.subject,
      html: body.html,
      category: body.category || "general",   // ✅ ADD
      favorite: false,                         // ✅ ADD
      variantOf: body.variantOf || null,       // ✅ ADD (A/B)
    })
  }

  // 📄 Get All Templates (EXISTING)
  @Get()
  async getAll() {
    return this.templateModel.find().sort({ createdAt: -1 })
  }

  // =====================================================
  // ⭐ TOGGLE FAVORITE (ADDED)
  // =====================================================
  @Patch(":id/favorite")
  async toggleFavorite(@Param("id") id: string) {
    const t = await this.templateModel.findById(id)
    if (!t) throw new Error("Template not found")

    t.favorite = !t.favorite
    return t.save()
  }

  // =====================================================
  // 📂 FILTER BY CATEGORY (ADDED)
  // =====================================================
  @Get("category/:name")
  async byCategory(@Param("name") name: string) {
    return this.templateModel.find({ category: name })
  }

  // =====================================================
  // 🧪 CLONE TEMPLATE (A/B TESTING) (ADDED)
  // =====================================================
  @Post(":id/clone")
  async clone(@Param("id") id: string) {
    const t = await this.templateModel.findById(id)
    if (!t) throw new Error("Template not found")

    return this.templateModel.create({
      name: t.name + " (Variant)",
      subject: t.subject,
      html: t.html,
      category: t.category,
      favorite: false,
     variantOf: t._id.toString(), // ✅ FIX

    })
  }
@Post("ai-improve-subject")
async aiImproveSubject(@Body() body: any) {
  if (!body.subject) throw new Error("Subject required")

  // 🔮 future me OpenAI / GPT connect hoga
  const improved = `🔥 ${body.subject} – Don’t Miss This`

  return {
    original: body.subject,
    improved,
  }
}
  // =====================================================
  // 🧠 AI TEMPLATE GENERATOR (STUB – ADDED)
  // =====================================================
  @Post("ai-generate")
  async aiGenerate(@Body() body: any) {
    if (!body.prompt) throw new Error("Prompt required")

    // 🔮 later OpenAI connect hoga
    return {
      subject: "AI Generated Subject",
      html: `<p>${body.prompt}</p><p>Generated by AI ✨</p>`,
    }
  }
}
